[project]
name = "mem0-live"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.71.0",
    "google-generativeai>=0.8.6",
    "langchain>=1.2.15",
    "langchain-groq>=1.1.2",
    "mem0ai>=1.0.11",
    "python-dotenv>=1.2.2",
    "streamlit>=1.56.0",
]
